name: $(Build.SourceBranchName).$(Date:yyyyMMdd)$(rev:rr)
"on":
  push:
    branches:
    - refs/heads/main
    - refs/heads/develop
  pull_request:
    branches:
    - main
env:
  buildPlatform: Any CPU
  buildConfiguration: Release
  defaultPipelineAgentHost: default
jobs:
  TemplateJob_deploy-stages_Terraform-Validate_yml:
    runs-on: ubuntu-latest
    steps:
    - name: Run template deploy-stages/Terraform-Validate.yml
      run: echo Running template deploy-stages/Terraform-Validate.yml
  TestJob:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: dotnet test --configuration $(buildConfiguration)
  DeployJob:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to environment
      run: echo "Deploying to environment"
  BuildJob:
    runs-on: ubuntu-latest
    steps:
    - name: 
      run: 
    - name: Build project
      run: dotnet build --configuration $(buildConfiguration)

